--Credenciales ADMIN
--Usuario: ADMIN
--Clave: Duoc_DFS3_2025

--Ejecutar como ADMIN
--Creación de un nuevo usuario
CREATE USER USER_DFSIII IDENTIFIED BY DUOC_ActSum_DFS3
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA;
GRANT CONNECT, RESOURCE TO USER_DFSIII;
COMMIT;

--Ejecutar como USER_DFSIII despues de iniciar el proyecto
--Usuarios
INSERT INTO USUARIOS (NOMBRE, EMAIL, ROL, FECHA_REGISTRO) VALUES ('Ana Perez', 'ana.perez@gmail.com', 'ADMIN', SYSTIMESTAMP);
INSERT INTO USUARIOS (NOMBRE, EMAIL, ROL, FECHA_REGISTRO) VALUES ('Luis Gomez', 'luis.gomez@gmail.com', 'USER', SYSTIMESTAMP);
INSERT INTO USUARIOS (NOMBRE, EMAIL, ROL, FECHA_REGISTRO) VALUES ('Carla Rojas', 'carla.rojas@gmail.com', 'USER', SYSTIMESTAMP);
COMMIT;

--Laboratorios
INSERT INTO LABORATORIOS (NOMBRE, CAPACIDAD, ESTADO, TIPO_ANALISIS) VALUES ('Lab Central', 100, 'ACTIVO', 'Química');
INSERT INTO LABORATORIOS (NOMBRE, CAPACIDAD, ESTADO, TIPO_ANALISIS) VALUES ('Lab Norte', 50, 'ACTIVO', 'Hematología');
INSERT INTO LABORATORIOS (NOMBRE, CAPACIDAD, ESTADO, TIPO_ANALISIS) VALUES ('Lab Sur', 30, 'INACTIVO', 'Microbiología');
COMMIT;